### PR TITLE
Update plugin to new conventions

### PR DESCRIPTION
**Pull request by donny-dont**
Instead of downloading and using the manifest tool mimic the behavior of the CLI commands used. This is now possible with the v2 of the manifest tool library which can be used in this manner.

Use the new coding conventions for the plugin.

### CODE REVIEW

**Comment by donny-dont** [comment]
For sure a tag should be pushed before this lands.

Also the actual machinations of how to push the manifest came from https://github.com/estesp/manifest-tool/blob/main/v2/cmd/manifest-tool/push.go which in v2 made the executable like a library so it could be used by this. Removing the exe download is definitely good since I experienced some issues with it on Windows.

**Comment by tphoney** [comment]
Great work, @donny-dont do you think we should make this as a major release ? ie V2.0.0. I know that this doesnt follow semver. It has the same functionality, and it should behave as normal. (no backwards breaking changes) 
likely we will leave this to soak as latest for a while anyway.
I will tag a release now

**Comment by donny-dont** [comment]
I don't think there was ever any sort of conclusion on how to do breaking changes in these plugins, especially the notification ones aka drone-slack. One of the reasons I did the whole `lint` reporting is so we can maybe move towards deprecating some stuff.

This doesn't have any breaking changes so I think we're ok just keeping it as latest for the moment.

**Comment by tphoney** [comment]
https://hub.docker.com/r/plugins/manifest/tags
https://harness.drone.io/drone-plugins/drone-manifest/26

**Review by tphoney — APPROVED** [review]

**Pull request merged**
