### PR TITLE
Implemented inital version

### PR DESCRIPTION
**Pull request by tboerger**
You can see the first use already at https://github.com/drone-plugins/drone-manifest/blob/8a125cd50e58d19757f77e41abf35ba6e090882b/.drone.yml#L129-L137 as I have pushed an initial tag manually.
 
Edit: The manifest definition is built by a template you can see at https://github.com/drone-plugins/drone-manifest/blob/1c2751de68af11d44403943cf4d1708869041ff4/manifest.tmpl, it's using the same templating as the notification plugins.

### CODE REVIEW

**Comment by tboerger** [comment]
I would suggest to merge it even if appveyor currently fails.

**Comment by appleboy** [comment]
@tboerger appveyor fix the build problem?

**Comment by tboerger** [comment]
> @tboerger appveyor fix the build problem?

The matrix plugin still fails, so this seems to be not affecting all repos. The PRs https://github.com/drone-plugins/drone-codecov/pull/2 and https://github.com/drone-plugins/drone-codacy/pull/3 also build fine on appveyor.

**Comment by tonglil** [comment]
Would be great to get docs in https://github.com/drone/drone-plugin-index :)

**Comment by tboerger** [comment]
@tonglil i will provide the docs for the latest plugins pretty soon, maybe i can finish it today.

**Pull request merged**
